name: Generate leaderboard
run-name: generate-leaderboard

on:
  workflow_run:
    workflows: ["*"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  generate-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download leaderboard-raw-data JSON artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: get-raw-leaderboard-data.yml
          name: leaderboard_raw
          path: ./data
        continue-on-error: true

      - name: Download leaderboard-user-prompts JSON artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: get-raw-leaderboard-data.yml
          name: leaderboard_user_prompts
          path: ./data
        continue-on-error: true

      - name: Install Anthropic Claude LLM
        run: |
          python -m pip install llm llm-claude-3

      - name: Generate leaderboard with LLM
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Test Claude LLM communication first
          echo "Testing Claude LLM connection..."
          echo "Hello LLM" | llm prompt -m claude-3-haiku -s "Just respond with 'LLM connection successful'"

          # Check if JSON file exists
          if [ -f "./data/leaderboard_raw.jsonnet" ]; then
            echo "Processing leaderboard data and user promtps..."

            cat ./data/leaderboard_raw.jsonnet && cat ./data/leaderboard_user_prompts.jsonnet | llm prompt -m claude-3-haiku -s "
            You are tasked with creating a leaderboard from leaderboard_raw data in JSON format.
            Additionally, you have leaderboard_user_prompts data that can influence the final order or presentation of the leaderboard.

            Please analyze the JSON data and generate:
            1. A ranked leaderboard showing participant rankings
            2. Summary statistics (total participants, completion rates, etc.)
            3. Progress breakdown by challenge phase
            4. Notable achievements or milestones reached

            Format the output as clean, readable markdown that could be used in a README or website.
            Include appropriate emojis and formatting to make it engaging.

            JSON Data:
            " > leaderboard.md

            echo "Leaderboard generated successfully!"
            cat leaderboard.md
          else
            echo "No JSON file found. Skipping leaderboard generation."
            echo "Expected file: ./data/leaderboard_raw.jsonnet"
          fi

      - name: Upload leaderboard
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard
          path: leaderboard.md
          retention-days: 30