name: Get raw leaderboard data
run-name: get-raw-leaderboard-data

on:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: '0 9 * * *'

jobs:
  get-raw-leaderboard-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install bq client
        run: gcloud components install bq --quiet

      - name: Create leaderboard_raw.jsonnet using BigQuery
        run: |
          echo "Running BigQuery command..."
          if bq query --format=json --max_rows=5000 --use_legacy_sql=false --headless --project_id=sap-opc <"$(pwd)"/bq_leaderboard_raw.sql > "$(pwd)"/leaderboard_raw.jsonnet 2>&1; then
            echo "BigQuery command succeeded"
          else
            echo "BigQuery command failed with error:"
            bq query --format=json --max_rows=5000 --use_legacy_sql=false --headless --project_id=sap-opc <"$(pwd)"/bq_leaderboard_raw.sql 2>&1 || true
            exit 1
          fi

      - name: Upload leaderboard_raw.jsonnet data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard_raw
          path: leaderboard_raw.jsonnet
          retention-days: 1