name: Get leaderboard data
run-name: get-leaderboard-data

on:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: '0 9 * * *'

jobs:
  get-raw-leaderboard-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install bq client
        run: gcloud components install bq --quiet

      - name: Create leaderboard_raw JSON file
        run: |
          echo "Checking if SQL file exists..."
          ls -la bq_leaderboard.sql

          echo "SQL file contents:"
          cat bq_leaderboard.sql

          echo "Running BigQuery command..."
          if bq query --format=json --max_rows=5000 --use_legacy_sql=false --headless --project_id=sap-opc <"$(pwd)"/bq_leaderboard.sql > "$(pwd)"/leaderboard_raw.jsonnet 2>&1; then
            echo "BigQuery command succeeded"
            echo "Generated file:"
            ls -la leaderboard_raw.jsonnet
            cat leaderboard_raw.jsonnet
          else
            echo "BigQuery command failed with error:"
            bq query --format=json --max_rows=5000 --use_legacy_sql=false --headless --project_id=sap-opc <"$(pwd)"/bq_leaderboard.sql 2>&1 || true
            echo "Checking if file was created anyway:"
            ls -la leaderboard_raw.jsonnet || echo "No file created"
            exit 1
          fi

      - name: Upload leaderboard data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard_raw
          path: leaderboard_raw.jsonnet
          retention-days: 7